spring.batch.initialize-schema=always
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/terra001
spring.datasource.schema=terra001
spring.datasource.username=postgres
spring.datasource.password=terra
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

# DDL generation
spring.jpa.generate-ddl=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.security.user.name=joao
spring.security.user.password=terra

# Context API
server.servlet.contextPath=/api
